services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: stream
      POSTGRES_PASSWORD: stream
      POSTGRES_DB: eventflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  
  prodcuer:
    build: ./producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC: "events"
    restart: unless-stopped

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC: "events"
      KAFKA_GROUP_ID: "eventflow-consumers"
      POSTGRES_DSN: "dbname=eventflow user=stream password=stream host=postgres port=5432"
    restart: unless-stopped

  api:
    build: ./api
    depends_on:
      - postgres
    environment:
      POSTGRES_DSN: "dbname=eventflow user=stream password=stream host=postgres port=5432"
    ports:
      - "8000:8000"
    restart: unless-stopped